just added more functions and variables
The-Code-Breakers/What-Do-You-Want pull request #8
Opened 2019-09-14 20:33 UTC by XD3V

I added more a function for validating no info. I also added new variables for showModal. As well as adding a current date.

2019-09-14 20:55 UTC, SirHexxus requested changes
Line 106-107: Should be `||` not `&`

2019-09-14 21:06 UTC, XD3V reviewed
I added the new library for us as well as make change to the code from changin "&" to "||"

2019-09-15 03:40 UTC, XD3V reviewed
in this push I am just showing how the RegExp is working to validate the users response. Also, i found and fixed that typo on line 121 with the 2 "||" so you will not have to worry about that on the next push.

2019-09-16 07:19 UTC, XD3V reviewed
Also, I moved the pseudo code for the event cards in the submit button so, it can all be done in one call

2019-09-16 21:56 UTC, SirHexxus requested changes

2019-09-16 21:56 UTC, SirHexxus commented on app.js
> +   if( (userDate == "" ) & (userState == "") & (pickedTime == "") & (userCity == "")){
status = true

if ( userDate == "" ) {
  // Please Enter Date
  status = false
}

if ( userState == "" ) {
  // Please Enter State
  status = false
}

if ( pickedTime == "" ) {
  // Please Choose Time
  status = false
}

if ( userCity == "" ) {
  // Please Enter City
  status = false
}

2019-09-17 02:22 UTC, SirHexxus approved these changes

2019-09-17 02:22 UTC, SirHexxus commented on app.js
>     if( (userDate == "" ) || (userState == "") || (pickedTime == "") || (userCity == "")){
Change this to individual conditions, with `status = true;` by default, and if any condition is true, it sets `status = false;`

2019-09-17 02:22 UTC, SirHexxus commented on app.js
>  <script src="VerbalExpressions.js"></script>
Remove, and add to Index.html

2019-09-17 02:22 UTC, merged